Allow change of layout for NAD
powsybl/powsybl-dev-tools pull request #114
Opened 2024-04-18 13:20 UTC by tadam50

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**
'Fixes #113 '

2024-04-24 12:49 UTC, So-Fras requested changes

2024-04-24 12:49 UTC, So-Fras commented on diagram-viewer/src/main/java/com/powsybl/diagram/viewer/nad/NetworkAreaDiagramModel.java
> +            case BASIC_LAYOUT -> new BasicForceLayoutFactory();
"basic", for "BasicForceLayoutFactory" is not very self-explanatory. I would name it FORCE_LAYOUT for example. And I would change the displayed value to from "Basic" to "Force Layout" (see suggestion below).

2024-04-24 12:49 UTC, So-Fras commented on diagram-viewer/src/main/resources/nad/view.fxml
>                                      <String fx:value="Basic"/>
```suggestion
                                    <String fx:value="Force layout"/>
```

2024-04-26 14:06 UTC, flo-dup commented on diagram-viewer/src/main/java/com/powsybl/diagram/viewer/nad/NetworkAreaDiagramModel.java
> +        // FIXME : user must be able to customize positions
indeed! myabe we could have an open file dialog then, to choose a data file. But we still have to define the format. As this feature is already needed now in the viewer, let's keep that for later

2024-04-26 14:08 UTC, flo-dup approved these changes

2024-04-29 07:38 UTC, merged