update powsybl-core and powsybl-diagram versions in pom files
powsybl/powsybl-dev-tools pull request #73
Opened 2023-02-01 10:06 UTC by So-Fras

Signed-off-by: Sophie Frasnedo <sophie.frasnedo@rte-france.com>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
update versions of powsybl-core and powsybl-diagram in pom files

2023-02-01 10:24 UTC, flo-dup requested changes

2023-02-01 10:24 UTC, flo-dup commented on network-area-diagram-viewer/pom.xml
> +        <powsybl.diagram.version>3.1.0</powsybl.diagram.version>
```suggestion
        <powsybl.diagram.version>3.2.0-SNAPSHOT</powsybl.diagram.version>
```

The primary goal of these viewers is to be used with latest snapshot version of tested artifact, so you shouldn't refer to a release.

2023-02-01 10:24 UTC, flo-dup commented on power-factory-viewer/pom.xml
> +        <powsybl-core.version>5.1.0</powsybl-core.version>
```suggestion
        <powsybl-core.version>5.2.0-SNAPSHOT</powsybl-core.version>
```

2023-02-01 10:24 UTC, flo-dup commented on single-line-diagram-viewer/pom.xml
> +        <powsybl-diagram.version>3.1.0</powsybl-diagram.version>
```suggestion
        <powsybl-diagram.version>3.2.0-SNAPSHOT</powsybl-diagram.version>
```

2023-02-01 15:49 UTC, So-Fras commented
The CI is ok, both versions (powsybl-core and powsybl-diagram) seem ok too. 
@flo-dup do you approve the changes ?

2023-02-01 16:08 UTC, flo-dup reviewed
I think that for power-factory-viewer you'd rather use 5.2.0-SNAPSHOT, isn't it @geofjamg ?

2023-02-03 14:54 UTC, flo-dup approved these changes

2023-02-03 14:57 UTC, merged